# This is a manually-triggered workflow for computing the redshift of every FRB and storing it in the catalogue.

name: Compute redshifts

on:
  workflow_dispatch:

jobs:
  compute_redshifts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Send greeting
      run: echo "-------------------------\nInstalling dependencies...\n-------------------------";sudo apt-get install f2c;sudo pip3 install astropy;sudo pip3 install numpy;sudo pip3 install scipy;sudo pip3 install pygedm;sudo pip3 install fruitbat;echo "-------------------------\nFetching catalogue...\n-------------------------";git clone https://github.com/HeRTA/FRBSTATS.git;cd FRBSTATS;echo "-------------------------\nComputing redshifts...\n-------------------------";python3 redshifts.py;echo "-------------------------\nCommitting catalogue.csv...\n-------------------------";git config user.name github-actions;git config user.email github-actions@github.com;git add . ;git commit -m "[BOT] Recomputed redshifts";git push;echo "-------------------------\nJob complete!\n-------------------------"
