# This is a manually-triggered workflow for computing the redshift of every FRB and storing it in the catalogue.

name: Compute redshifts

on:
  workflow_dispatch:

jobs:
  compute_redshifts:
    runs-on: ubuntu-latest

    steps:
    - name: Compute redshifts
      run: echo "-------------------------";echo "Installing dependencies...";echo "-------------------------";sudo apt-get install f2c;sudo pip3 install astropy;sudo pip3 install numpy;sudo pip3 install scipy;sudo pip3 install pygedm;sudo pip3 install fruitbat;echo "-------------------------";echo "Fetching catalogue..."; echo "-------------------------";git clone https://github.com/HeRTA/FRBSTATS.git;cd FRBSTATS;echo "Computing redshifts..."; echo "-------------------------";touch catalogue.csv;python3 fetch_catalogue.py;python3 redshifts.py;echo "-------------------------";echo "Committing catalogue.csv...";echo "--------------------------------------------------"
