# This is a manually-triggered workflow for computing the redshift of every FRB and storing it in the catalogue.

name: Compare with TNS

on:
  workflow_dispatch:

jobs:
  tns_compare:
    runs-on: ubuntu-latest

    steps:
    - name: Compare with TNS
      run: echo "-------------------------";echo "Comparing TNS event count with FRBSTATS...";echo "-------------------------";sudo pip3 install requests;echo "-------------------------";git clone https://github.com/HeRTA/FRBSTATS.git;cd FRBSTATS;python3 tns_compare.py;echo "Job complete!";echo "-------------------------"
