# This is a workflow for automatically checking whether the FRBSTATS catalog is up-to-date with the TNS database on a daily basis.

name: Compare with TNS

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  tns_compare:
    runs-on: ubuntu-latest

    steps:
    - name: Compare with TNS
      run: echo "-------------------------";echo "Comparing TNS event count with FRBSTATS...";echo "-------------------------";sudo pip3 install requests;sudo pip3 install frbcat;sudo pip3 install astropy;echo "-------------------------";git clone https://github.com/HeRTA/FRBSTATS.git;cd FRBSTATS;python3 tns_compare.py;echo "Job complete!";echo "-------------------------"
