# This is a workflow for automatically checking whether the FRBSTATS catalog is up-to-date with the TNS database on a daily basis.

name: Compare with TNS

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 12 * * *'

jobs:
  tns_compare:
    runs-on: ubuntu-latest

    steps:
    - name: Compare with TNS
      run: echo "-------------------------";echo "Comparing TNS event count with FRBSTATS...";echo "-------------------------";sudo pip3 install requests;sudo pip3 install frbcat;sudo pip3 install astropy;sudo apt-get install f2c;sudo pip3 install numpy;sudo pip3 install scipy;sudo pip3 install pygedm;sudo pip3 install fruitbat;sudo pip3 install google-api-python-client google-auth-httplib2 google-auth-oauthlib;python3 -c "import frbcat;print(frbcat.__file__)";wget https://raw.githubusercontent.com/HeRTA/frbcat/master/frbcat/tns.py -O /usr/local/lib/python3.10/dist-packages/frbcat/tns.py;echo "-------------------------";git clone https://github.com/HeRTA/FRBSTATS.git;cd FRBSTATS;python3 tns_compare.py;echo "Job complete!";echo "-------------------------"
